spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: never

jwt:
  token:
    expires: 60000000
    secret: bilingual6
    issuer: peaksoft house

server:
  port: 8080
